#!/bin/bash
# install pip
sudo apt-get install python-pip
# install one-wire DS18B20 library
sudo pip install w1thermsensor
# enable one wire on pin 14 (usually done via raspi-config)
sudo dtoverlay w1-gpio gpiopin=14 pullup=0

# run python script
sudo python3 record_temp.py
